name: Build and test each chapter

on:
  workflow_dispatch:

jobs:


  build-and-test:
    strategy:
      fail-fast: true
      matrix:
        os: [macos-latest, ubuntu-latest]
        chapter: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
    uses: nlsandler/nqcc2/.github/workflows/build_and_test.yaml@main
    with:
      chapter: ${{ matrix.chapter }}
      os: ${{ matrix.os }}
